trigger:
  batch: true
  branches:
    include:
      - master
    exclude:
      - develop
      - staging

# Explicitly disable PR triggers if you only want the build to run POST-merge
pr: none

pool:
  name: Default

variables:
  RestoreBuildProjects: '**/dotsee.responsiveimages.csproj'
  BuildConfiguration: "Release"

steps:
- checkout: self
  fetchDepth: 0
  displayName: "Checkout solution"
  persistCredentials: true
  clean: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: "restore"
    feedsToUse: "config"    
    verbosityRestore: Detailed
    verbosityPack: Detailed

# - task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1
#   displayName: 'Mirror Git Repository to https://github.com/DotSee/DotSee.ResponsiveImages'
#   inputs:
#     sourceGitRepositoryUri: 'https://dev.azure.com/DotSeeWebServices/_git/DotSee.ResponsiveImages'
#     sourceGitRepositoryPersonalAccessToken: 4iayLLNN6KfaJnPRXyXlOK38MYkD4CKXi2SzpRDnadzvKb5JeEEAJQQJ99BEACAAAAAM3hCKAAASAZDOKRCS
#     sourceGitRepositoryCloneDirectoryName: Discipline
#     destinationGitRepositoryUri: 'https://github.com/DotSee/DotSee.ResponsiveImages'
#     destinationGitRepositoryPersonalAccessToken: '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'

- task: NuGetToolInstaller@1
  displayName: "Install 'Nuget' tool"
  inputs:
    versionSpec: "7.x"
    checkLatest: true

- task:  gitversion-setup@4
  displayName: "gitversion/setup"
  inputs:
    versionSpec: 6.x
    preferLatestVersion: true
    nugetConfigPath: 'nuget.config'
  
- task: gitversion-execute@4
  displayName: gitversion/execute
  inputs:
    # configFilePath: src/gitversion.yml
    updateAssemblyInfo: true

- script: |
    echo $(GitVersion_SemVer)
  displayName: "Print build version number"
  name: version_print

- task: GitTag@7
  displayName: 'GitTag '
  inputs:
    tagUser: 'Sotiris Filippidis'
    tagEmail: 'sotirisf@dot-see.com'
    tag: '$(GitVersion.Major).$(GitVersion.Minor).$(GitVersion.Patch)'
    tagMessage: '$(GitVersion.Major).$(GitVersion.Minor).$(GitVersion.Patch)'
    useLightweightTags: true
    forceTagCreation: true

- task: Assembly-Info-NetCore@3
  displayName: 'Set Assembly Manifest Data'
  inputs:
    PackageId: DotSee.ResponsiveImages
    Authors: DotSee
    Company: 'Dotsee Web Services SA'
    PackageLicenseExpression: MIT
    VersionNumber: "$(GitVersion_SemVer)"
    FileVersionNumber: "$(GitVersion_SemVer)"
    InformationalVersion: "$(GitVersion_SemVer)"
    PackageVersion: "$(GitVersion_SemVer)"
    Product: "Responsive Images"
    Copyright: "Copyright © $(date:YYYY) DotSee Web Services S.A."


- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    verbosityRestore: Detailed
    packagesToPack: src/DotSee.ResponsiveImages/DotSee.ResponsiveImages.csproj
    configuration: "$(BuildConfiguration)"
    packDirectory: "$(Build.ArtifactStagingDirectory)"
    nobuild: true
    versioningScheme: "byEnvVar"
    versionEnvVar: GitVersion_SemVer

- task: NuGetCommand@2
  displayName: 'NuGet push to LeNuget (dotsee)'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'DotSee LeNuget Server (PROD)'
  enabled: false

# - task: NuGetCommand@2
#   displayName: 'NuGet push to Nuget.org'
#   inputs:
#     command: push
#     nuGetFeedType: external
#     publishFeedCredentials: Nuget.org
